In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.shape

(569, 31)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-1.80253863,  1.48428853, -1.79601953, ..., -1.71146482,
         0.23698136,  0.85824812],
       [ 0.67869181,  0.21851513,  0.73108327, ...,  1.39497904,
         0.23073019,  0.6297081 ],
       [-0.52909989, -0.27320725, -0.546068  , ..., -0.36371087,
         0.48702836, -0.48790168],
       ...,
       [-0.78486755, -0.03322791, -0.81435631, ..., -0.64886257,
        -0.79133694, -0.94007274],
       [-1.01221657,  0.91963125, -1.01835433, ..., -1.23443106,
        -1.06170026, -0.86589269],
       [ 1.20443643, -0.14145389,  1.11435228, ...,  0.68667931,
         0.46827484, -0.7780766 ]])

In [9]:
y_train

538    B
177    M
367    B
240    B
529    B
      ..
133    B
369    M
67     B
299    B
186    M
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1])

#Numpy arrays to PyTorch tensors

In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

In [18]:
y_train_tensor.shape

torch.Size([455])

#defining the model

In [35]:
class MySimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights)+self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

#parameter

In [44]:
learning_rate = 0.1
epochs = 25

#pipeline

In [46]:
#cretae a model
model = MySimpleNN(X_train_tensor)

#define loop
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(X_train_tensor)
  #print(y_pred)

  #calculate loss
  loss = model.loss_function(y_pred,y_train_tensor)

  #backward pass
  loss.backward()

  #WEIGHTS UPDATE
  with torch.no_grad():
     model.weights -= learning_rate*model.weights.grad
     model.bias -= learning_rate*model.bias.grad

  #zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #accuracy
  print(f"Epochs:{epoch+1},loss:{loss.item()}")

Epochs:1,loss:4.049091449575486
Epochs:2,loss:3.8392938431195063
Epochs:3,loss:3.6302152782048984
Epochs:4,loss:3.4223262008017086
Epochs:5,loss:3.215815085829425
Epochs:6,loss:3.0109737268517396
Epochs:7,loss:2.8081532754493455
Epochs:8,loss:2.607796923984695
Epochs:9,loss:2.4104633844289864
Epochs:10,loss:2.216859484124478
Epochs:11,loss:2.0278821513428604
Epochs:12,loss:1.8446736266399153
Epochs:13,loss:1.6686937026187953
Epochs:14,loss:1.5018098032833278
Epochs:15,loss:1.3464009887360024
Epochs:16,loss:1.2054541330641442
Epochs:17,loss:1.082467668559993
Epochs:18,loss:0.9806236220424633
Epochs:19,loss:0.9014175149843621
Epochs:20,loss:0.8438164317862286
Epochs:21,loss:0.8042026299031036
Epochs:22,loss:0.7778404453737701
Epochs:23,loss:0.7604301526015217
Epochs:24,loss:0.7487184990358985
Epochs:25,loss:0.7405171275365476

In [47]:
model.weights

tensor([[ 0.3216],
        [ 0.0810],
        [-0.1108],
        [-0.2163],
        [ 0.1418],
        [-0.5139],
        [ 0.2578],
        [-0.2296],
        [ 0.1869],
        [-0.0578],
        [-0.1657],
        [ 0.0088],
        [-0.1881],
        [-0.3728],
        [ 0.5387],
        [ 0.0853],
        [ 0.2797],
        [ 0.2008],
        [ 0.1457],
        [-0.3115],
        [ 0.3321],
        [-0.0431],
        [ 0.0200],
        [ 0.4129],
        [ 0.0997],
        [-0.4772],
        [ 0.2391],
        [-0.0294],
        [-0.0363],
        [ 0.3552]], dtype=torch.float64, requires_grad=True)

In [48]:
model.bias

tensor([-0.1805], dtype=torch.float64, requires_grad=True)

In [51]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5877193212509155